language: node_js
node_js:
  - '14'
  - '12'
  - '10'
script:
  - npm run compile
  - npm run lint
  - npm run coverage
after_script:
  - npm install coveralls
  - cat ./coverage/lcov.info | coveralls
